spring:
  datasource:
    hikari:
      maximum-pool-size: 6
      connection-timeout: 60000
      connection-init-sql: "SET lock_timeout = '60s'; SET statement_timeout = '60s'; SET idle_in_transaction_session_timeout = '90s'"

wallet:
  transaction-timeout-seconds: 60